### ISSUE TITLE
Updating to properties

### ISSUE THREAD

**Issue by mehdigreefhorst** [cameronking4/notion-openapi-chatgpt-action#3]
Heey! 

Super great integration. It worked super quickly. I also added my database id to the GPT and it worked even better. Now I'm working making the GPT have access to the properties. Have you managed to update properties of a page in a database? I have not yet been able to. Some properties you cannot update but custom ones seem to be possible based on the documentation.

**Comment by rolliver** [comment]
Yeah it's been really helpful.

I have managed to update properties, but I'm not 100% sure how I did it.

I think it was by adding a property to update

```
PageUpdate:
      type: object
      properties:
        properties:
          type: object
*** Added this part:
          properties:
            Done:
              type: object
              required:
                - checkbox
              properties:
                checkbox:
                  type: boolean
                  const: true
                  example: true
***
          additionalProperties: true
```

then I think even after it had an example of one it was able to update other properties.

I had to do the same thing with the query too.

Like I say, don't know how I got it going and I don't know it won't break again as soon as I write this ;P
